apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
      - name: order-svc
        image: wonderrfau1t/order-service:v2
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: REDIS_ADDR
          value: "redis-service:6379"
        - name: PORT
          value: "8080"